spring:
  application:
    name: demo

  datasource:
    #mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/demodb?characterEncoding=utf-8&useSSL=false&autoReconnect=true

  redis:
    host: localhost
    port: 6379
    password: password

mybatis:
  configuration:
    #mybatis自动匹配DB中字段的_和entity中的驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    #打印出sql语句
    com.example.lucifer.mapper: debug
